// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAplikacijaZaUgostiteljskeObjekte.Server.Core;

#nullable disable

namespace WebAplikacijaZaUgostiteljskeObjekte.Server.Migrations
{
    [DbContext(typeof(Data))]
    [Migration("20220908193303_UgostiteljskiObjektiUpdate2")]
    partial class UgostiteljskiObjektiUpdate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UgostiteljskiObjektId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("UgostiteljskiObjektId");

                    b.HasIndex("UserId");

                    b.ToTable("Komentari");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Drinks", b =>
                {
                    b.Property<int>("DrinksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrinksId"), 1L, 1);

                    b.Property<decimal>("Cjena")
                        .HasColumnType("money");

                    b.Property<string>("NazivPica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PiceNormativ")
                        .HasColumnType("real");

                    b.Property<int>("UgostiteljskiObjektiId")
                        .HasColumnType("int");

                    b.HasKey("DrinksId");

                    b.HasIndex("UgostiteljskiObjektiId");

                    b.ToTable("Pica");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Jela", b =>
                {
                    b.Property<int>("JelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JelaId"), 1L, 1);

                    b.Property<decimal>("Cjena")
                        .HasColumnType("money");

                    b.Property<string>("NazivJela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UgostiteljskiObjektiId")
                        .HasColumnType("int");

                    b.HasKey("JelaId");

                    b.HasIndex("UgostiteljskiObjektiId");

                    b.ToTable("Jela");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Ocjene", b =>
                {
                    b.Property<int>("OcjeneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OcjeneId"), 1L, 1);

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<DateTime>("OcjenaVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<int>("UgostiteljskiObjektiId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OcjeneId");

                    b.HasIndex("UgostiteljskiObjektiId");

                    b.HasIndex("UserId");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.PrijavljeniBugovi", b =>
                {
                    b.Property<int>("BugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BugId"), 1L, 1);

                    b.Property<int>("BugStaus")
                        .HasColumnType("int");

                    b.Property<string>("BugText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BugVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserIdBug")
                        .HasColumnType("int");

                    b.HasKey("BugId");

                    b.HasIndex("UserIdBug");

                    b.ToTable("PrijavljeniBugovi");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.UgostiteljskiObjekti", b =>
                {
                    b.Property<int>("UgostiteljskiObjektiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UgostiteljskiObjektiId"), 1L, 1);

                    b.Property<string>("UgostiteljskiObjektiEmali")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiGrad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiKontakt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UgostiteljskiObjektiKucniBroj")
                        .HasColumnType("int");

                    b.Property<float>("UgostiteljskiObjektiLatituda")
                        .HasColumnType("real");

                    b.Property<float>("UgostiteljskiObjektiLongituda")
                        .HasColumnType("real");

                    b.Property<string>("UgostiteljskiObjektiLozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiOIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("UgostiteljskiObjektiProsjecnaOcjena")
                        .HasColumnType("real");

                    b.Property<string>("UgostiteljskiObjektiRadnoVrijeme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiRadnoVrijemeNed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiRadnoVrijemePraznici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiRadnoVrijemeSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiSlika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiStanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiTip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiUlica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UgostiteljskiObjektiVlasnik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UgostiteljskiObjektiId");

                    b.ToTable("UgostiteljskiObjekti");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Comment", b =>
                {
                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.UgostiteljskiObjekti", "UgostiteljskiObjekti")
                        .WithMany()
                        .HasForeignKey("UgostiteljskiObjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UgostiteljskiObjekti");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Drinks", b =>
                {
                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.UgostiteljskiObjekti", "UgostiteljskiObjekti")
                        .WithMany()
                        .HasForeignKey("UgostiteljskiObjektiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UgostiteljskiObjekti");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Jela", b =>
                {
                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.UgostiteljskiObjekti", "UgostiteljskiObjekti")
                        .WithMany()
                        .HasForeignKey("UgostiteljskiObjektiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UgostiteljskiObjekti");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.Ocjene", b =>
                {
                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.UgostiteljskiObjekti", "UgostiteljskiObjekti")
                        .WithMany()
                        .HasForeignKey("UgostiteljskiObjektiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UgostiteljskiObjekti");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.PrijavljeniBugovi", b =>
                {
                    b.HasOne("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdBug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAplikacijaZaUgostiteljskeObjekte.Server.Core.Entities.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
